services:
  db:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_DB: vep_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    # Use service_healthy to ensure the database is ready
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql+psycopg2://user:password@db:5432/vep_db
    volumes:
      - .:/app
    # Override the CMD from the Dockerfile to run our script
    command: ["python", "src/import_vep_data.py"]